apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: {{REPLICAS}}  
  selector:
    matchLabels:  
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MYSQL_DATABASE
          value: devops
        ports:
        - containerPort: 3306
          name: mysql
        
--- 
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
