apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: {{REPLICAS}}  
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: aziz1123/opsautomateback:latest 
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/devops
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: 
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8082
  selector:
    app: spring-boot-app
